name = "stagifyai"
pages_build_output_dir = ".next"
compatibility_date = "2024-01-01"

[env.production]
vars = { ENVIRONMENT = "production" }

[env.staging]
vars = { ENVIRONMENT = "staging" }

[[d1_databases]]
binding = "DB"
database_name = "stagifyai-db"
database_id = "5a786b75-d719-4e0d-9709-2eeda52011f1"

[[r2_buckets]]
binding = "STORAGE"
bucket_name = "stagifyai-storage"